### ISSUE TITLE
发送消息即断开连接,无法正常联通

### ISSUE THREAD

**Issue by didiEvans** [lazyboyl/websocket-spring-boot-starter#3]
正常启动项目,socket连接成功,但是一发消息就断开连接,报io异常. 不知道是我消息格式有问题还是什么

传递的参数
`
连接成功，现在你可以发送信息啦！！！
你发送的信息 2021-02-03 10:31:41
{'url': '/org/getOrgVo/', 'params': {'orgId': 'sada11d', 'orgName': '林泽锋'}
websocket连接已断开!!!
连接成功，现在你可以发送信息啦！！！
你发送的信息 2021-02-03 10:32:05
{'url': '/org/getOrgVo', 'params': {'orgId': 'sada11d', 'orgName': '林泽锋'}}
websocket连接已断开!!!
连接成功，现在你可以发送信息啦！！！
你发送的信息 2021-02-03 10:33:37
{'orgId': 'sada11d', 'orgName': '林泽锋'}
websocket连接已断开!!!
`

后端报错信息
`
java.lang.ClassCastException: io.netty.handler.codec.http.websocketx.TextWebSocketFrame cannot be cast to io.netty.handler.codec.http.FullHttpRequest
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler.channelRead(WebSocketServerProtocolHandshakeHandler.java:63) ~[netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

与客户端断开连接，通道关闭！3c7c3ffffe2be523-000026dc-00000003-3dac060cc7129468-ba1525bd
当前关闭的通道的id是：3c7c3ffffe2be523-000026dc-00000003-3dac060cc7129468-ba1525bd
2021-02-03 10:33:37.535  INFO 9948 --- [ntLoopGroup-3-3] c.v.d.vue.service.WebSocketCloseService  : 将我从聊天组中移除操作！3c7c3ffffe2be523-000026dc-00000003-3dac060cc7129468-ba1525bd
2021-02-03 10:33:37.535  INFO 9948 --- [ntLoopGroup-3-3] c.v.d.vue.service.WebSocketCloseService  : 将我进行下线操作！3c7c3ffffe2be523-000026dc-00000003-3dac060cc7129468-ba1525bd
`

谢谢解惑

**Comment by didiEvans** [comment]
就是我的传参问题, 脑子秀逗了, 没好好看文档, 打扰了. 大佬
