### ISSUE TITLE
websocket-spring-boot-core-1.0.6.release，初始化bean配置报错

### ISSUE THREAD

**Issue by pan003** [lazyboyl/websocket-spring-boot-starter#5]
idea项目启动调试报错，应该是NettyScanner类加载写的有问题；但是打出来的jar包，用java -jar命令行启动没问题

java.lang.ClassNotFoundException: com.vue.demo.vue./Users/apple/code/learn/websocket-spring-boot-starter/vue-example/netty-websocket-vue-back/target/classes/com/vue/demo/vue/security.WebSocketHandlerListenterImpl
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.lazyboyl.websocket.util.NettyScanner$1.loadClass(NettyScanner.java:183)
	at com.github.lazyboyl.websocket.util.NettyScanner.doAddClass(NettyScanner.java:186)
	at com.github.lazyboyl.websocket.util.NettyScanner.addClass(NettyScanner.java:168)
	at com.github.lazyboyl.websocket.util.NettyScanner.addClass(NettyScanner.java:160)
	at com.github.lazyboyl.websocket.util.NettyScanner.initClasses(NettyScanner.java:93)
	at com.github.lazyboyl.websocket.server.NettySocketServer.initWebSocketConfig(NettySocketServer.java:182)
	at com.github.lazyboyl.websocket.server.NettySocketServer.init(NettySocketServer.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:893)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.vue.demo.vue.VueDemoApplication.main(VueDemoApplication.java:12)
2022-03-24 10:13:47.132  INFO 66834 --- [           main] com.vue.demo.vue.VueDemoApplication      : Started VueDemoApplication in 1.078 seconds (JVM running for 1.858)

**Comment by pan003** [comment]
已解决，扫描class，文件分割符写死，不兼容linux、mac
this.addClass(classes, f.getPath(), packageName + "." + fileName.split(File.separator)[fileName.split(File.separator).length - 1]);

**Comment by Faker0715** [comment]
大佬，这个是在linux不能使用吗

**Comment by Faker0715** [comment]
> 已解决，扫描class，文件分割符写死，不兼容linux、mac this.addClass(classes, f.getPath(), packageName + "." + fileName.split(File.separator)[fileName.split(File.separator).length - 1]);

大佬，这个是在linux不能使用吗，还是要改代码，这行代码没找到呀
