### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by Faker0715** [lazyboyl/websocket-spring-boot-starter#8]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-01-10 22:54:13.605 ERROR 11152 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nettySocketServer': Invocation of init method failed; nested exception is java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.3.jar:2.7.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.3.jar:2.7.3]
	at com.hw.hwbackend.HwBackendApplication.main(HwBackendApplication.java:14) ~[classes/:na]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837) ~[na:na]
	at com.github.lazyboyl.websocket.factory.WebSocketControllerBeanFactory.parseUrl(WebSocketControllerBeanFactory.java:188) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.factory.WebSocketControllerBeanFactory.parseNettyRequestMapping(WebSocketControllerBeanFactory.java:157) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.factory.WebSocketControllerBeanFactory.registerNettyMethodDefinition(WebSocketControllerBeanFactory.java:135) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.factory.WebSocketControllerBeanFactory.registerNettyBeanDefinition(WebSocketControllerBeanFactory.java:64) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.factory.NettyDefaultBeanFactory.registerBean(NettyDefaultBeanFactory.java:91) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.server.NettySocketServer.injectionBean(NettySocketServer.java:206) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.server.NettySocketServer.initWebSocketConfig(NettySocketServer.java:185) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at com.github.lazyboyl.websocket.server.NettySocketServer.init(NettySocketServer.java:120) ~[websocket-spring-boot-core-1.0.6.RELEASE.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.22.jar:5.3.22]
	... 18 common frames omitted

Process finished with exit code 1

**Comment by Faker0715** [comment]
明白了 
![image](https://user-images.githubusercontent.com/36560441/211586155-c3399be1-fce4-47b1-9bec-c654e519a350.png)
![image](https://user-images.githubusercontent.com/36560441/211586206-9ce95df0-b17a-4ae6-b8d0-7801063972b6.png)
这里我想请求服务器地址就是localhost:端口/ 
然后请求localhost:端口/getCpuData
但是好像这样不行 必须这里注解加上随便一个后缀
![image](https://user-images.githubusercontent.com/36560441/211586613-6850558c-7ee8-4da4-88e3-c2d87a2f2fc3.png)

**Comment by Faker0715** [comment]
现在遇到一个无法自动装配的问题，代码都差不多的。
![dabc1061356f7093211d10227b5b330](https://user-images.githubusercontent.com/36560441/211620166-da4d2421-85d4-4750-bac2-a247aec5fa39.png)
![image](https://user-images.githubusercontent.com/36560441/211620237-f9a7cb6f-9678-4a59-87c4-e1244d1b632c.png)
求大佬解答
